# -*- coding: utf-8 -*-
"""Automatically Email.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwPfHA5EfE1BYRTE_gkaUj0Z6YySBR_v
"""

import os
import smtplib
import ssl
from email.message import EmailMessage

# Setup email account
email_sender = 'sender@gmail.com'
email_password = os.getenv('EMAIL_PASSWORD') # It's safer to load sensitive info as environment variable
email_receiver = 'receiver@gmail.com'

# Email subject/body
subject = 'Basic Information'
body = message['text']

# Create EmailMessage object
em = EmailMessage()
em['From'] = email_sender
em['To'] = email_receiver 
em['Subject'] = subject
em.set_content(body)

# Create a secure SSL context
context = ssl.create_default_context()

# Send email
with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
    smtp.login(email_sender, email_password)
    smtp.sendmail(email_sender, email_receiver, em.as_string())