# -*- coding: utf-8 -*-
"""Python slack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRQY_Op60vCz_myMqmCahl0K9wZNMgdq
"""

import slack_sdk

# Your bot user token, which you saved when you installed the app
bot_token = 'xoxb-XXXX-XXXX'

# Initialize a Web API client
slack_client = slack_sdk.WebClient(token=bot_token)

# Specify the ID of the channel you want to grab text from
channel_id = 'CXXXXXXXX'

# Call the conversations.history method using the WebClient
result = slack_client.conversations_history(channel=channel_id)

# Get only messages from the response (excluding other types like user joins, etc.)
messages = [message for message in result.data['messages'] if message.get('type') == 'message' and 'subtype' not in message]

# Print each message
for message in messages:
    print(message['text'])